### ISSUE TITLE
Unable to open GUI tab, i can see it in the windows tab however my first gu tab is non responsive and i am unable to go to the new gui tab generated

### ISSUE THREAD

**Issue by pushprg** [jjpaulo2/windows-time-sync#7]
i can see the gui table window tab created after event in the windows tab however my main gui tab is non responsive and i am unable to go to the new gui tab created
[main.txt](https://github.com/jjpaulo2/windows-time-sync/files/10950303/main.txt)
[table.txt](https://github.com/jjpaulo2/windows-time-sync/files/10950304/table.txt)

**Comment by jjpaulo2** [comment]
Hi. This issue is not related to the project, and I am going to close it now.
